const dummyData = [
  {
    domiOriEnvio: 'DTC',
    sucOrigenEnvio: 'A0040',
    secueEnvio: 23430,
    numSec: 34534543,
    dominioDest: 'RD',
    sucursalDest: '',
    fullDate: 20191915,
    time: '14:30',
    montoImposicion: 200,
    monedaImposicion: 'US$',
    tasaCambio: 50.63,
    monedaEntrega: 'RD$',
    montoEntrega: '',
    mensaje: 'alimentacion',
    idRemitente: '',
    nombreRemitente: 'Denis Santana',
    telRemitente: '718-512-5788',
    direcRemitente: 'Calle 5, #3',
    sectorRemitente: 'La Vigía',
    ciudadRemitente: 'Corona',
    estadoRemitente: 'New York',
    paisRemitente: 'Estados Unidos',
    idBenef: '',
    nombreBenef: 'Carlos Santana',
    telfBenef: '',
    direcBenef: 'Calle 5, #3',
    sectorBenef: 'Los Prados',
    ciudadBenef: 'Santo Domingo',
    estadoBenef: '',
    paisBenef: 'Republica Dominicana',
    tipoEntrega: 'O',
    tipoServicio: 'R',
    numOriEnvio: 'A005000002',
    nombreBanco: '',
    numCuentaBanco: '',
    fechaOperaciones: '',
    reservado: ''
  },
  {
    domiOriEnvio: 'DTC',
    sucOrigenEnvio: 'A0040',
    secueEnvio: 23432,
    numSec: 34534543,
    dominioDest: 'RD',
    sucursalDest: '',
    fullDate: 20191915,
    time: '14:31',
    montoImposicion: 300,
    monedaImposicion: 'US$',
    tasaCambio: 50.63,
    monedaEntrega: 'RD$',
    montoEntrega: '',
    mensaje: 'calamidad domestica',
    idRemitente: '',
    nombreRemitente: 'Carlos Rodriguez',
    telRemitente: '718-458-5815',
    direcRemitente: 'Calle 5, #3',
    sectorRemitente: 'La Vigía',
    ciudadRemitente: 'Corona',
    estadoRemitente: 'New York',
    paisRemitente: 'Estados Unidos',
    idBenef: '',
    nombreBenef: 'Denis Rodriguez',
    telfBenef: '20-257-0125',
    direcBenef: 'Calle 5, #3',
    sectorBenef: 'Los Prados',
    ciudadBenef: 'Santo Domingo',
    estadoBenef: '',
    paisBenef: 'Republica Dominicana',
    tipoEntrega: 'B',
    tipoServicio: 'R',
    numOriEnvio: 'A005000003',
    nombreBanco: 'Banco BHD',
    numCuentaBanco: '001-32454-23',
    fechaOperaciones: '',
    reservado: ''
  }
]

module.exports = dummyData
